#pragma kernel CSMain
#include "Packages/com.unity.render-pipelines.core/ShaderLibrary/Color.hlsl"

RWTexture2D<float4> inputRT;
RWTexture2D<float4> outputRT;
int width;
int height;
int offsetX;
int offsetY;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if(id.x >= width || id.x < 0 || id.y >= height || id.y < 0) return;

    outputRT[id.xy + uint2(offsetX, offsetY)] = inputRT[id.xy];
}